[package]
name = "texture-crab"
authors = ["Evan Kamuf"]
version = "0.0.1"
edition = "2021"
description = "Simple 2D & 3D texture sandbox."

[dependencies]
raylib = { version = "5.0" }
egui-file-dialog = { version = "0.9" }
