[package]
name = "Texture Crab"
authors = ["Evan Kamuf"]
version = "0.0.1"
edition = "2021"
description = "Author's introductory works with the Rust language."

[dependencies]
raylib = { version = "5.0" }
egui-file-dialog = { version = "0.9" }
